/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as VillaggioRouteImport } from './routes/villaggio'
import { Route as SpedizioniRouteImport } from './routes/spedizioni'
import { Route as RicordiRouteImport } from './routes/ricordi'
import { Route as RicetteRouteImport } from './routes/ricette'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as ProfiloRouteImport } from './routes/profilo'
import { Route as PremiRouteImport } from './routes/premi'
import { Route as PikminRouteImport } from './routes/pikmin'
import { Route as NemiciRouteImport } from './routes/nemici'
import { Route as NavicellaRouteImport } from './routes/navicella'
import { Route as MissioniRouteImport } from './routes/missioni'
import { Route as MercatoRouteImport } from './routes/mercato'
import { Route as MappaRouteImport } from './routes/mappa'
import { Route as LabRouteImport } from './routes/lab'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BaseRouteImport } from './routes/base'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as ArchivioRouteImport } from './routes/archivio'
import { Route as AgentiRouteImport } from './routes/agenti'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VillaggioScambiRouteImport } from './routes/villaggio.scambi'
import { Route as VillaggioPhaserRouteImport } from './routes/villaggio.phaser'
import { Route as VillaggioEdificiRouteImport } from './routes/villaggio.edifici'
import { Route as VillaggioAgentRouteImport } from './routes/villaggio.$agent'
import { Route as SpedizioniKeyRouteImport } from './routes/spedizioni.$key'
import { Route as VillaggioEditorBiomeRouteImport } from './routes/villaggio.editor.$biome'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const VillaggioRoute = VillaggioRouteImport.update({
  id: '/villaggio',
  path: '/villaggio',
  getParentRoute: () => rootRouteImport,
} as any)
const SpedizioniRoute = SpedizioniRouteImport.update({
  id: '/spedizioni',
  path: '/spedizioni',
  getParentRoute: () => rootRouteImport,
} as any)
const RicordiRoute = RicordiRouteImport.update({
  id: '/ricordi',
  path: '/ricordi',
  getParentRoute: () => rootRouteImport,
} as any)
const RicetteRoute = RicetteRouteImport.update({
  id: '/ricette',
  path: '/ricette',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfiloRoute = ProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiRoute = PremiRouteImport.update({
  id: '/premi',
  path: '/premi',
  getParentRoute: () => rootRouteImport,
} as any)
const PikminRoute = PikminRouteImport.update({
  id: '/pikmin',
  path: '/pikmin',
  getParentRoute: () => rootRouteImport,
} as any)
const NemiciRoute = NemiciRouteImport.update({
  id: '/nemici',
  path: '/nemici',
  getParentRoute: () => rootRouteImport,
} as any)
const NavicellaRoute = NavicellaRouteImport.update({
  id: '/navicella',
  path: '/navicella',
  getParentRoute: () => rootRouteImport,
} as any)
const MissioniRoute = MissioniRouteImport.update({
  id: '/missioni',
  path: '/missioni',
  getParentRoute: () => rootRouteImport,
} as any)
const MercatoRoute = MercatoRouteImport.update({
  id: '/mercato',
  path: '/mercato',
  getParentRoute: () => rootRouteImport,
} as any)
const MappaRoute = MappaRouteImport.update({
  id: '/mappa',
  path: '/mappa',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseRoute = BaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivioRoute = ArchivioRouteImport.update({
  id: '/archivio',
  path: '/archivio',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentiRoute = AgentiRouteImport.update({
  id: '/agenti',
  path: '/agenti',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VillaggioScambiRoute = VillaggioScambiRouteImport.update({
  id: '/scambi',
  path: '/scambi',
  getParentRoute: () => VillaggioRoute,
} as any)
const VillaggioPhaserRoute = VillaggioPhaserRouteImport.update({
  id: '/phaser',
  path: '/phaser',
  getParentRoute: () => VillaggioRoute,
} as any)
const VillaggioEdificiRoute = VillaggioEdificiRouteImport.update({
  id: '/edifici',
  path: '/edifici',
  getParentRoute: () => VillaggioRoute,
} as any)
const VillaggioAgentRoute = VillaggioAgentRouteImport.update({
  id: '/$agent',
  path: '/$agent',
  getParentRoute: () => VillaggioRoute,
} as any)
const SpedizioniKeyRoute = SpedizioniKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => SpedizioniRoute,
} as any)
const VillaggioEditorBiomeRoute = VillaggioEditorBiomeRouteImport.update({
  id: '/editor/$biome',
  path: '/editor/$biome',
  getParentRoute: () => VillaggioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenti': typeof AgentiRoute
  '/archivio': typeof ArchivioRoute
  '/atelier': typeof AtelierRoute
  '/base': typeof BaseRoute
  '/chat': typeof ChatRoute
  '/index': typeof Char91indexChar93Route
  '/inventario': typeof InventarioRoute
  '/lab': typeof LabRoute
  '/mappa': typeof MappaRoute
  '/mercato': typeof MercatoRoute
  '/missioni': typeof MissioniRoute
  '/navicella': typeof NavicellaRoute
  '/nemici': typeof NemiciRoute
  '/pikmin': typeof PikminRoute
  '/premi': typeof PremiRoute
  '/profilo': typeof ProfiloRoute
  '/radar': typeof RadarRoute
  '/ricette': typeof RicetteRoute
  '/ricordi': typeof RicordiRoute
  '/spedizioni': typeof SpedizioniRouteWithChildren
  '/villaggio': typeof VillaggioRouteWithChildren
  '/spedizioni/$key': typeof SpedizioniKeyRoute
  '/villaggio/$agent': typeof VillaggioAgentRoute
  '/villaggio/edifici': typeof VillaggioEdificiRoute
  '/villaggio/phaser': typeof VillaggioPhaserRoute
  '/villaggio/scambi': typeof VillaggioScambiRoute
  '/villaggio/editor/$biome': typeof VillaggioEditorBiomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenti': typeof AgentiRoute
  '/archivio': typeof ArchivioRoute
  '/atelier': typeof AtelierRoute
  '/base': typeof BaseRoute
  '/chat': typeof ChatRoute
  '/index': typeof Char91indexChar93Route
  '/inventario': typeof InventarioRoute
  '/lab': typeof LabRoute
  '/mappa': typeof MappaRoute
  '/mercato': typeof MercatoRoute
  '/missioni': typeof MissioniRoute
  '/navicella': typeof NavicellaRoute
  '/nemici': typeof NemiciRoute
  '/pikmin': typeof PikminRoute
  '/premi': typeof PremiRoute
  '/profilo': typeof ProfiloRoute
  '/radar': typeof RadarRoute
  '/ricette': typeof RicetteRoute
  '/ricordi': typeof RicordiRoute
  '/spedizioni': typeof SpedizioniRouteWithChildren
  '/villaggio': typeof VillaggioRouteWithChildren
  '/spedizioni/$key': typeof SpedizioniKeyRoute
  '/villaggio/$agent': typeof VillaggioAgentRoute
  '/villaggio/edifici': typeof VillaggioEdificiRoute
  '/villaggio/phaser': typeof VillaggioPhaserRoute
  '/villaggio/scambi': typeof VillaggioScambiRoute
  '/villaggio/editor/$biome': typeof VillaggioEditorBiomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenti': typeof AgentiRoute
  '/archivio': typeof ArchivioRoute
  '/atelier': typeof AtelierRoute
  '/base': typeof BaseRoute
  '/chat': typeof ChatRoute
  '/index': typeof Char91indexChar93Route
  '/inventario': typeof InventarioRoute
  '/lab': typeof LabRoute
  '/mappa': typeof MappaRoute
  '/mercato': typeof MercatoRoute
  '/missioni': typeof MissioniRoute
  '/navicella': typeof NavicellaRoute
  '/nemici': typeof NemiciRoute
  '/pikmin': typeof PikminRoute
  '/premi': typeof PremiRoute
  '/profilo': typeof ProfiloRoute
  '/radar': typeof RadarRoute
  '/ricette': typeof RicetteRoute
  '/ricordi': typeof RicordiRoute
  '/spedizioni': typeof SpedizioniRouteWithChildren
  '/villaggio': typeof VillaggioRouteWithChildren
  '/spedizioni/$key': typeof SpedizioniKeyRoute
  '/villaggio/$agent': typeof VillaggioAgentRoute
  '/villaggio/edifici': typeof VillaggioEdificiRoute
  '/villaggio/phaser': typeof VillaggioPhaserRoute
  '/villaggio/scambi': typeof VillaggioScambiRoute
  '/villaggio/editor/$biome': typeof VillaggioEditorBiomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenti'
    | '/archivio'
    | '/atelier'
    | '/base'
    | '/chat'
    | '/index'
    | '/inventario'
    | '/lab'
    | '/mappa'
    | '/mercato'
    | '/missioni'
    | '/navicella'
    | '/nemici'
    | '/pikmin'
    | '/premi'
    | '/profilo'
    | '/radar'
    | '/ricette'
    | '/ricordi'
    | '/spedizioni'
    | '/villaggio'
    | '/spedizioni/$key'
    | '/villaggio/$agent'
    | '/villaggio/edifici'
    | '/villaggio/phaser'
    | '/villaggio/scambi'
    | '/villaggio/editor/$biome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenti'
    | '/archivio'
    | '/atelier'
    | '/base'
    | '/chat'
    | '/index'
    | '/inventario'
    | '/lab'
    | '/mappa'
    | '/mercato'
    | '/missioni'
    | '/navicella'
    | '/nemici'
    | '/pikmin'
    | '/premi'
    | '/profilo'
    | '/radar'
    | '/ricette'
    | '/ricordi'
    | '/spedizioni'
    | '/villaggio'
    | '/spedizioni/$key'
    | '/villaggio/$agent'
    | '/villaggio/edifici'
    | '/villaggio/phaser'
    | '/villaggio/scambi'
    | '/villaggio/editor/$biome'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenti'
    | '/archivio'
    | '/atelier'
    | '/base'
    | '/chat'
    | '/index'
    | '/inventario'
    | '/lab'
    | '/mappa'
    | '/mercato'
    | '/missioni'
    | '/navicella'
    | '/nemici'
    | '/pikmin'
    | '/premi'
    | '/profilo'
    | '/radar'
    | '/ricette'
    | '/ricordi'
    | '/spedizioni'
    | '/villaggio'
    | '/spedizioni/$key'
    | '/villaggio/$agent'
    | '/villaggio/edifici'
    | '/villaggio/phaser'
    | '/villaggio/scambi'
    | '/villaggio/editor/$biome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentiRoute: typeof AgentiRoute
  ArchivioRoute: typeof ArchivioRoute
  AtelierRoute: typeof AtelierRoute
  BaseRoute: typeof BaseRoute
  ChatRoute: typeof ChatRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  InventarioRoute: typeof InventarioRoute
  LabRoute: typeof LabRoute
  MappaRoute: typeof MappaRoute
  MercatoRoute: typeof MercatoRoute
  MissioniRoute: typeof MissioniRoute
  NavicellaRoute: typeof NavicellaRoute
  NemiciRoute: typeof NemiciRoute
  PikminRoute: typeof PikminRoute
  PremiRoute: typeof PremiRoute
  ProfiloRoute: typeof ProfiloRoute
  RadarRoute: typeof RadarRoute
  RicetteRoute: typeof RicetteRoute
  RicordiRoute: typeof RicordiRoute
  SpedizioniRoute: typeof SpedizioniRouteWithChildren
  VillaggioRoute: typeof VillaggioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villaggio': {
      id: '/villaggio'
      path: '/villaggio'
      fullPath: '/villaggio'
      preLoaderRoute: typeof VillaggioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spedizioni': {
      id: '/spedizioni'
      path: '/spedizioni'
      fullPath: '/spedizioni'
      preLoaderRoute: typeof SpedizioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ricordi': {
      id: '/ricordi'
      path: '/ricordi'
      fullPath: '/ricordi'
      preLoaderRoute: typeof RicordiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ricette': {
      id: '/ricette'
      path: '/ricette'
      fullPath: '/ricette'
      preLoaderRoute: typeof RicetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profilo': {
      id: '/profilo'
      path: '/profilo'
      fullPath: '/profilo'
      preLoaderRoute: typeof ProfiloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premi': {
      id: '/premi'
      path: '/premi'
      fullPath: '/premi'
      preLoaderRoute: typeof PremiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pikmin': {
      id: '/pikmin'
      path: '/pikmin'
      fullPath: '/pikmin'
      preLoaderRoute: typeof PikminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nemici': {
      id: '/nemici'
      path: '/nemici'
      fullPath: '/nemici'
      preLoaderRoute: typeof NemiciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navicella': {
      id: '/navicella'
      path: '/navicella'
      fullPath: '/navicella'
      preLoaderRoute: typeof NavicellaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missioni': {
      id: '/missioni'
      path: '/missioni'
      fullPath: '/missioni'
      preLoaderRoute: typeof MissioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercato': {
      id: '/mercato'
      path: '/mercato'
      fullPath: '/mercato'
      preLoaderRoute: typeof MercatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mappa': {
      id: '/mappa'
      path: '/mappa'
      fullPath: '/mappa'
      preLoaderRoute: typeof MappaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base': {
      id: '/base'
      path: '/base'
      fullPath: '/base'
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archivio': {
      id: '/archivio'
      path: '/archivio'
      fullPath: '/archivio'
      preLoaderRoute: typeof ArchivioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenti': {
      id: '/agenti'
      path: '/agenti'
      fullPath: '/agenti'
      preLoaderRoute: typeof AgentiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villaggio/scambi': {
      id: '/villaggio/scambi'
      path: '/scambi'
      fullPath: '/villaggio/scambi'
      preLoaderRoute: typeof VillaggioScambiRouteImport
      parentRoute: typeof VillaggioRoute
    }
    '/villaggio/phaser': {
      id: '/villaggio/phaser'
      path: '/phaser'
      fullPath: '/villaggio/phaser'
      preLoaderRoute: typeof VillaggioPhaserRouteImport
      parentRoute: typeof VillaggioRoute
    }
    '/villaggio/edifici': {
      id: '/villaggio/edifici'
      path: '/edifici'
      fullPath: '/villaggio/edifici'
      preLoaderRoute: typeof VillaggioEdificiRouteImport
      parentRoute: typeof VillaggioRoute
    }
    '/villaggio/$agent': {
      id: '/villaggio/$agent'
      path: '/$agent'
      fullPath: '/villaggio/$agent'
      preLoaderRoute: typeof VillaggioAgentRouteImport
      parentRoute: typeof VillaggioRoute
    }
    '/spedizioni/$key': {
      id: '/spedizioni/$key'
      path: '/$key'
      fullPath: '/spedizioni/$key'
      preLoaderRoute: typeof SpedizioniKeyRouteImport
      parentRoute: typeof SpedizioniRoute
    }
    '/villaggio/editor/$biome': {
      id: '/villaggio/editor/$biome'
      path: '/editor/$biome'
      fullPath: '/villaggio/editor/$biome'
      preLoaderRoute: typeof VillaggioEditorBiomeRouteImport
      parentRoute: typeof VillaggioRoute
    }
  }
}

interface SpedizioniRouteChildren {
  SpedizioniKeyRoute: typeof SpedizioniKeyRoute
}

const SpedizioniRouteChildren: SpedizioniRouteChildren = {
  SpedizioniKeyRoute: SpedizioniKeyRoute,
}

const SpedizioniRouteWithChildren = SpedizioniRoute._addFileChildren(
  SpedizioniRouteChildren,
)

interface VillaggioRouteChildren {
  VillaggioAgentRoute: typeof VillaggioAgentRoute
  VillaggioEdificiRoute: typeof VillaggioEdificiRoute
  VillaggioPhaserRoute: typeof VillaggioPhaserRoute
  VillaggioScambiRoute: typeof VillaggioScambiRoute
  VillaggioEditorBiomeRoute: typeof VillaggioEditorBiomeRoute
}

const VillaggioRouteChildren: VillaggioRouteChildren = {
  VillaggioAgentRoute: VillaggioAgentRoute,
  VillaggioEdificiRoute: VillaggioEdificiRoute,
  VillaggioPhaserRoute: VillaggioPhaserRoute,
  VillaggioScambiRoute: VillaggioScambiRoute,
  VillaggioEditorBiomeRoute: VillaggioEditorBiomeRoute,
}

const VillaggioRouteWithChildren = VillaggioRoute._addFileChildren(
  VillaggioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentiRoute: AgentiRoute,
  ArchivioRoute: ArchivioRoute,
  AtelierRoute: AtelierRoute,
  BaseRoute: BaseRoute,
  ChatRoute: ChatRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  InventarioRoute: InventarioRoute,
  LabRoute: LabRoute,
  MappaRoute: MappaRoute,
  MercatoRoute: MercatoRoute,
  MissioniRoute: MissioniRoute,
  NavicellaRoute: NavicellaRoute,
  NemiciRoute: NemiciRoute,
  PikminRoute: PikminRoute,
  PremiRoute: PremiRoute,
  ProfiloRoute: ProfiloRoute,
  RadarRoute: RadarRoute,
  RicetteRoute: RicetteRoute,
  RicordiRoute: RicordiRoute,
  SpedizioniRoute: SpedizioniRouteWithChildren,
  VillaggioRoute: VillaggioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
